services:
  database:
    container_name: "postgres-dev"
    image: "${POSTGRES_IMAGE:-public.ecr.aws/docker/library/postgres:16-alpine}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-hero_pet}"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 2s
      retries: 20
      start_period: 5s
